name: Bug Report
description: Report a bug in the project
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug"
      description: "Explain the issue and how to reproduce it."
